version: '3.7'

networks:
  app-net:
    external: true

services:
  web-api:
    image: web-api:latest
    environment:
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - FACEBOOK_SECRET=${FACEBOOK_SECRET}
      - VK_SECRET=${VK_SECRET}
    networks:
      - app-net
    ports:
      - "4321:4321"
      - "4200:4200"
    volumes:
      - .:/app
    command: npm run watch

# docker-compose up